services:
  web:
    build: .
    ports:
      - "80:8080"
    restart: always
  pipeline-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Changezi@123
