services:
  web:
    build: .
    ports:
      - "80:3000"
    # DELETE OR COMMENT OUT THE env_file: - .env LINE HERE
  pipeline-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Changezi@123
